"""Changed Columns to match collections

Revision ID: 5d352e051c4e
Revises: f1f47bab2274
Create Date: 2025-08-22 22:33:32.562227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d352e051c4e'
down_revision = 'f1f47bab2274'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boost_factors', 'astronomy_weight', new_column_name='astrophysics_weight')
    op.alter_column('boost_factors', 'earth_science_weight', new_column_name='earthscience_weight')
    op.alter_column('boost_factors', 'planetary_science_weight', new_column_name='planetary_weight')

    op.alter_column('boost_factors', 'astronomy_final_boost', new_column_name='astrophysics_final_boost')
    op.alter_column('boost_factors', 'planetary_science_final_boost', new_column_name='planetary_final_boost')
    op.alter_column('boost_factors', 'earth_science_final_boost', new_column_name='earthscience_final_boost')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boost_factors', 'astrophysics_weight', new_column_name='astronomy_weight')
    op.alter_column('boost_factors', 'astrophysics_final_boost', new_column_name='astronomy_final_boost')
    op.alter_column('boost_factors', 'earthscience_weight', new_column_name='earth_science_weight')
    op.alter_column('boost_factors', 'earthscience_final_boost', new_column_name='earth_science_final_boost')
    op.alter_column('boost_factors', 'planetary_weight', new_column_name='planetary_science_weight')
    op.alter_column('boost_factors', 'planetary_final_boost', new_column_name='planetary_science_final_boost')


    # ### end Alembic commands ### 